# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.DateField(verbose_name='上映日期'),
        ),
    ]
