# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_auto_20170519_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(default='無'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='無', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default='2小時', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='movietype',
            field=models.CharField(default='動畫', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='videourl',
            field=models.CharField(default='www.youtube.com', max_length=200),
        ),
    ]
