# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_auto_20170519_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='videourl',
            field=models.URLField(default='www.youtube.com'),
        ),
    ]
