# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-21 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_auto_20170519_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
